version: '3.7'
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3310:3310
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo_db
      MYSQL_TCP_PORT: 3310
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  web:
    hostname: web
    depends_on:
      - mysql
      - smtp
    build:
      context: .
      target: development
    environment:
      RAILS_MASTER_KEY:
      MYSQL_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo_db
    ports:
      - '3000:3000'
      # vscodeでデバッグする際に使用
      # - '1234:1234'
      # - '26162:26162'
    volumes:
      - '.:/usr/src/web'
      - bundle:/usr/local/bundle
      - /usr/src/web/node_modules
      - /usr/src/web/tmp/cache
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3310
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    # vscodeでデバッグする際のコマンド
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -p 3000 -b '0.0.0.0'"
  smtp:
    image: schickling/mailcatcher:latest
    platform: linux/amd64
    ports:
      - '1080:1080'
      - '1020:1025'
volumes:
  mysql:
  bundle:
